// Bangladesh districts & upazilas (source: bangladesh-geocode, CC0)
export interface BdDistrict { id: string; name: string; bn: string }
export interface BdUpazila { districtId: string; name: string; bn: string }

export const BD_DISTRICTS: BdDistrict[] = [
  { id: "28", name: "Bagerhat", bn: "বাগেরহাট" },
  { id: "11", name: "Bandarban", bn: "বান্দরবান" },
  { id: "35", name: "Barguna", bn: "বরগুনা" },
  { id: "33", name: "Barisal", bn: "বরিশাল" },
  { id: "34", name: "Bhola", bn: "ভোলা" },
  { id: "14", name: "Bogura", bn: "বগুড়া" },
  { id: "3", name: "Brahmanbaria", bn: "ব্রাহ্মণবাড়িয়া" },
  { id: "6", name: "Chandpur", bn: "চাঁদপুর" },
  { id: "18", name: "Chapainawabganj", bn: "চাঁপাইনবাবগঞ্জ" },
  { id: "8", name: "Chattogram", bn: "চট্টগ্রাম" },
  { id: "24", name: "Chuadanga", bn: "চুয়াডাঙ্গা" },
  { id: "1", name: "Comilla", bn: "কুমিল্লা" },
  { id: "9", name: "Coxsbazar", bn: "কক্সবাজার" },
  { id: "47", name: "Dhaka", bn: "ঢাকা" },
  { id: "54", name: "Dinajpur", bn: "দিনাজপুর" },
  { id: "52", name: "Faridpur", bn: "ফরিদপুর" },
  { id: "2", name: "Feni", bn: "ফেনী" },
  { id: "57", name: "Gaibandha", bn: "গাইবান্ধা" },
  { id: "41", name: "Gazipur", bn: "গাজীপুর" },
  { id: "51", name: "Gopalganj", bn: "গোপালগঞ্জ" },
  { id: "38", name: "Habiganj", bn: "হবিগঞ্জ" },
  { id: "63", name: "Jamalpur", bn: "জামালপুর" },
  { id: "20", name: "Jashore", bn: "যশোর" },
  { id: "30", name: "Jhalakathi", bn: "ঝালকাঠি" },
  { id: "29", name: "Jhenaidah", bn: "ঝিনাইদহ" },
  { id: "17", name: "Joypurhat", bn: "জয়পুরহাট" },
  { id: "10", name: "Khagrachhari", bn: "খাগড়াছড়ি" },
  { id: "27", name: "Khulna", bn: "খুলনা" },
  { id: "45", name: "Kishoreganj", bn: "কিশোরগঞ্জ" },
  { id: "60", name: "Kurigram", bn: "কুড়িগ্রাম" },
  { id: "25", name: "Kushtia", bn: "কুষ্টিয়া" },
  { id: "7", name: "Lakshmipur", bn: "লক্ষ্মীপুর" },
  { id: "55", name: "Lalmonirhat", bn: "লালমনিরহাট" },
  { id: "50", name: "Madaripur", bn: "মাদারীপুর" },
  { id: "26", name: "Magura", bn: "মাগুরা" },
  { id: "46", name: "Manikganj", bn: "মানিকগঞ্জ" },
  { id: "22", name: "Meherpur", bn: "মেহেরপুর" },
  { id: "37", name: "Moulvibazar", bn: "মৌলভীবাজার" },
  { id: "48", name: "Munshiganj", bn: "মুন্সিগঞ্জ" },
  { id: "62", name: "Mymensingh", bn: "ময়মনসিংহ" },
  { id: "19", name: "Naogaon", bn: "নওগাঁ" },
  { id: "23", name: "Narail", bn: "নড়াইল" },
  { id: "43", name: "Narayanganj", bn: "নারায়ণগঞ্জ" },
  { id: "40", name: "Narsingdi", bn: "নরসিংদী" },
  { id: "16", name: "Natore", bn: "নাটোর" },
  { id: "64", name: "Netrokona", bn: "নেত্রকোণা" },
  { id: "56", name: "Nilphamari", bn: "নীলফামারী" },
  { id: "5", name: "Noakhali", bn: "নোয়াখালী" },
  { id: "13", name: "Pabna", bn: "পাবনা" },
  { id: "53", name: "Panchagarh", bn: "পঞ্চগড়" },
  { id: "31", name: "Patuakhali", bn: "পটুয়াখালী" },
  { id: "32", name: "Pirojpur", bn: "পিরোজপুর" },
  { id: "49", name: "Rajbari", bn: "রাজবাড়ী" },
  { id: "15", name: "Rajshahi", bn: "রাজশাহী" },
  { id: "4", name: "Rangamati", bn: "রাঙ্গামাটি" },
  { id: "59", name: "Rangpur", bn: "রংপুর" },
  { id: "21", name: "Satkhira", bn: "সাতক্ষীরা" },
  { id: "42", name: "Shariatpur", bn: "শরীয়তপুর" },
  { id: "61", name: "Sherpur", bn: "শেরপুর" },
  { id: "12", name: "Sirajganj", bn: "সিরাজগঞ্জ" },
  { id: "39", name: "Sunamganj", bn: "সুনামগঞ্জ" },
  { id: "36", name: "Sylhet", bn: "সিলেট" },
  { id: "44", name: "Tangail", bn: "টাঙ্গাইল" },
  { id: "58", name: "Thakurgaon", bn: "ঠাকুরগাঁও" },
]

export const BD_UPAZILAS: BdUpazila[] = [
  { districtId: "1", name: "Barura", bn: "বরুড়া" },
  { districtId: "1", name: "Brahmanpara", bn: "ব্রাহ্মণপাড়া" },
  { districtId: "1", name: "Burichang", bn: "বুড়িচং" },
  { districtId: "1", name: "Chandina", bn: "চান্দিনা" },
  { districtId: "1", name: "Chauddagram", bn: "চৌদ্দগ্রাম" },
  { districtId: "1", name: "Comilla Sadar", bn: "কুমিল্লা সদর" },
  { districtId: "1", name: "Daudkandi", bn: "দাউদকান্দি" },
  { districtId: "1", name: "Debidwar", bn: "দেবিদ্বার" },
  { districtId: "1", name: "Homna", bn: "হোমনা" },
  { districtId: "1", name: "Laksam", bn: "লাকসাম" },
  { districtId: "1", name: "Lalmai", bn: "লালমাই" },
  { districtId: "1", name: "Meghna", bn: "মেঘনা" },
  { districtId: "1", name: "Monohargonj", bn: "মনোহরগঞ্জ" },
  { districtId: "1", name: "Muradnagar", bn: "মুরাদনগর" },
  { districtId: "1", name: "Nangalkot", bn: "নাঙ্গলকোট" },
  { districtId: "1", name: "Sadarsouth", bn: "সদর দক্ষিণ" },
  { districtId: "1", name: "Titas", bn: "তিতাস" },
  { districtId: "2", name: "Chhagalnaiya", bn: "ছাগলনাইয়া" },
  { districtId: "2", name: "Daganbhuiyan", bn: "দাগনভূঞা" },
  { districtId: "2", name: "Feni Sadar", bn: "ফেনী সদর" },
  { districtId: "2", name: "Fulgazi", bn: "ফুলগাজী" },
  { districtId: "2", name: "Parshuram", bn: "পরশুরাম" },
  { districtId: "2", name: "Sonagazi", bn: "সোনাগাজী" },
  { districtId: "3", name: "Akhaura", bn: "আখাউড়া" },
  { districtId: "3", name: "Ashuganj", bn: "আশুগঞ্জ" },
  { districtId: "3", name: "Bancharampur", bn: "বাঞ্ছারামপুর" },
  { districtId: "3", name: "Bijoynagar", bn: "বিজয়নগর" },
  { districtId: "3", name: "Brahmanbaria Sadar", bn: "ব্রাহ্মণবাড়িয়া সদর" },
  { districtId: "3", name: "Kasba", bn: "কসবা" },
  { districtId: "3", name: "Nabinagar", bn: "নবীনগর" },
  { districtId: "3", name: "Nasirnagar", bn: "নাসিরনগর" },
  { districtId: "3", name: "Sarail", bn: "সরাইল" },
  { districtId: "4", name: "Baghaichari", bn: "বাঘাইছড়ি" },
  { districtId: "4", name: "Barkal", bn: "বরকল" },
  { districtId: "4", name: "Belaichari", bn: "বিলাইছড়ি" },
  { districtId: "4", name: "Juraichari", bn: "জুরাছড়ি" },
  { districtId: "4", name: "Kaptai", bn: "কাপ্তাই" },
  { districtId: "4", name: "Kawkhali", bn: "কাউখালী" },
  { districtId: "4", name: "Langadu", bn: "লংগদু" },
  { districtId: "4", name: "Naniarchar", bn: "নানিয়ারচর" },
  { districtId: "4", name: "Rajasthali", bn: "রাজস্থলী" },
  { districtId: "4", name: "Rangamati Sadar", bn: "রাঙ্গামাটি সদর" },
  { districtId: "5", name: "Begumganj", bn: "বেগমগঞ্জ" },
  { districtId: "5", name: "Chatkhil", bn: "চাটখিল" },
  { districtId: "5", name: "Companiganj", bn: "কোম্পানীগঞ্জ" },
  { districtId: "5", name: "Hatia", bn: "হাতিয়া" },
  { districtId: "5", name: "Kabirhat", bn: "কবিরহাট" },
  { districtId: "5", name: "Noakhali Sadar", bn: "নোয়াখালী সদর" },
  { districtId: "5", name: "Senbug", bn: "সেনবাগ" },
  { districtId: "5", name: "Sonaimori", bn: "সোনাইমুড়ী" },
  { districtId: "5", name: "Subarnachar", bn: "সুবর্ণচর" },
  { districtId: "6", name: "Chandpur Sadar", bn: "চাঁদপুর সদর" },
  { districtId: "6", name: "Faridgonj", bn: "ফরিদগঞ্জ" },
  { districtId: "6", name: "Haimchar", bn: "হাইমচর" },
  { districtId: "6", name: "Hajiganj", bn: "হাজীগঞ্জ" },
  { districtId: "6", name: "Kachua", bn: "কচুয়া" },
  { districtId: "6", name: "Matlab North", bn: "মতলব উত্তর" },
  { districtId: "6", name: "Matlab South", bn: "মতলব দক্ষিণ" },
  { districtId: "6", name: "Shahrasti", bn: "শাহরাস্তি\t" },
  { districtId: "7", name: "Kamalnagar", bn: "কমলনগর" },
  { districtId: "7", name: "Lakshmipur Sadar", bn: "লক্ষ্মীপুর সদর" },
  { districtId: "7", name: "Raipur", bn: "রায়পুর" },
  { districtId: "7", name: "Ramganj", bn: "রামগঞ্জ" },
  { districtId: "7", name: "Ramgati", bn: "রামগতি" },
  { districtId: "8", name: "Anwara", bn: "আনোয়ারা" },
  { districtId: "8", name: "Banshkhali", bn: "বাঁশখালী" },
  { districtId: "8", name: "Boalkhali", bn: "বোয়ালখালী" },
  { districtId: "8", name: "Chandanaish", bn: "চন্দনাইশ" },
  { districtId: "8", name: "Fatikchhari", bn: "ফটিকছড়ি" },
  { districtId: "8", name: "Hathazari", bn: "হাটহাজারী" },
  { districtId: "8", name: "Karnafuli", bn: "কর্ণফুলী" },
  { districtId: "8", name: "Lohagara", bn: "লোহাগাড়া" },
  { districtId: "8", name: "Mirsharai", bn: "মীরসরাই" },
  { districtId: "8", name: "Patiya", bn: "পটিয়া" },
  { districtId: "8", name: "Rangunia", bn: "রাঙ্গুনিয়া" },
  { districtId: "8", name: "Raozan", bn: "রাউজান" },
  { districtId: "8", name: "Sandwip", bn: "সন্দ্বীপ" },
  { districtId: "8", name: "Satkania", bn: "সাতকানিয়া" },
  { districtId: "8", name: "Sitakunda", bn: "সীতাকুন্ড" },
  { districtId: "9", name: "Chakaria", bn: "চকরিয়া" },
  { districtId: "9", name: "Coxsbazar Sadar", bn: "কক্সবাজার সদর" },
  { districtId: "9", name: "Eidgaon", bn: "ঈদগাঁও" },
  { districtId: "9", name: "Kutubdia", bn: "কুতুবদিয়া" },
  { districtId: "9", name: "Moheshkhali", bn: "মহেশখালী" },
  { districtId: "9", name: "Pekua", bn: "পেকুয়া" },
  { districtId: "9", name: "Ramu", bn: "রামু" },
  { districtId: "9", name: "Teknaf", bn: "টেকনাফ" },
  { districtId: "9", name: "Ukhiya", bn: "উখিয়া" },
  { districtId: "10", name: "Dighinala", bn: "দিঘীনালা" },
  { districtId: "10", name: "Guimara", bn: "গুইমারা" },
  { districtId: "10", name: "Khagrachhari Sadar", bn: "খাগড়াছড়ি সদর" },
  { districtId: "10", name: "Laxmichhari", bn: "লক্ষীছড়ি" },
  { districtId: "10", name: "Manikchari", bn: "মানিকছড়ি" },
  { districtId: "10", name: "Matiranga", bn: "মাটিরাঙ্গা" },
  { districtId: "10", name: "Mohalchari", bn: "মহালছড়ি" },
  { districtId: "10", name: "Panchari", bn: "পানছড়ি" },
  { districtId: "10", name: "Ramgarh", bn: "রামগড়" },
  { districtId: "11", name: "Alikadam", bn: "আলীকদম" },
  { districtId: "11", name: "Bandarban Sadar", bn: "বান্দরবান সদর" },
  { districtId: "11", name: "Lama", bn: "লামা" },
  { districtId: "11", name: "Naikhongchhari", bn: "নাইক্ষ্যংছড়ি" },
  { districtId: "11", name: "Rowangchhari", bn: "রোয়াংছড়ি" },
  { districtId: "11", name: "Ruma", bn: "রুমা" },
  { districtId: "11", name: "Thanchi", bn: "থানচি" },
  { districtId: "12", name: "Belkuchi", bn: "বেলকুচি" },
  { districtId: "12", name: "Chauhali", bn: "চৌহালি" },
  { districtId: "12", name: "Kamarkhand", bn: "কামারখন্দ" },
  { districtId: "12", name: "Kazipur", bn: "কাজীপুর" },
  { districtId: "12", name: "Raigonj", bn: "রায়গঞ্জ" },
  { districtId: "12", name: "Shahjadpur", bn: "শাহজাদপুর" },
  { districtId: "12", name: "Sirajganj Sadar", bn: "সিরাজগঞ্জ সদর" },
  { districtId: "12", name: "Tarash", bn: "তাড়াশ" },
  { districtId: "12", name: "Ullapara", bn: "উল্লাপাড়া" },
  { districtId: "13", name: "Atghoria", bn: "আটঘরিয়া" },
  { districtId: "13", name: "Bera", bn: "বেড়া" },
  { districtId: "13", name: "Bhangura", bn: "ভাঙ্গুড়া" },
  { districtId: "13", name: "Chatmohar", bn: "চাটমোহর" },
  { districtId: "13", name: "Faridpur", bn: "ফরিদপুর" },
  { districtId: "13", name: "Ishurdi", bn: "ঈশ্বরদী" },
  { districtId: "13", name: "Pabna Sadar", bn: "পাবনা সদর" },
  { districtId: "13", name: "Santhia", bn: "সাঁথিয়া" },
  { districtId: "13", name: "Sujanagar", bn: "সুজানগর" },
  { districtId: "14", name: "Adamdighi", bn: "আদমদিঘি" },
  { districtId: "14", name: "Bogra Sadar", bn: "বগুড়া সদর" },
  { districtId: "14", name: "Dhunot", bn: "ধুনট" },
  { districtId: "14", name: "Dupchanchia", bn: "দুপচাচিঁয়া" },
  { districtId: "14", name: "Gabtali", bn: "গাবতলী" },
  { districtId: "14", name: "Kahaloo", bn: "কাহালু" },
  { districtId: "14", name: "Nondigram", bn: "নন্দিগ্রাম" },
  { districtId: "14", name: "Shajahanpur", bn: "শাজাহানপুর" },
  { districtId: "14", name: "Shariakandi", bn: "সারিয়াকান্দি" },
  { districtId: "14", name: "Sherpur", bn: "শেরপুর" },
  { districtId: "14", name: "Shibganj", bn: "শিবগঞ্জ" },
  { districtId: "14", name: "Sonatala", bn: "সোনাতলা" },
  { districtId: "15", name: "Bagha", bn: "বাঘা" },
  { districtId: "15", name: "Bagmara", bn: "বাগমারা" },
  { districtId: "15", name: "Charghat", bn: "চারঘাট" },
  { districtId: "15", name: "Durgapur", bn: "দুর্গাপুর" },
  { districtId: "15", name: "Godagari", bn: "গোদাগাড়ী" },
  { districtId: "15", name: "Mohonpur", bn: "মোহনপুর" },
  { districtId: "15", name: "Paba", bn: "পবা" },
  { districtId: "15", name: "Puthia", bn: "পুঠিয়া" },
  { districtId: "15", name: "Tanore", bn: "তানোর" },
  { districtId: "16", name: "Bagatipara", bn: "বাগাতিপাড়া" },
  { districtId: "16", name: "Baraigram", bn: "বড়াইগ্রাম" },
  { districtId: "16", name: "Gurudaspur", bn: "গুরুদাসপুর" },
  { districtId: "16", name: "Lalpur", bn: "লালপুর" },
  { districtId: "16", name: "Naldanga", bn: "নলডাঙ্গা" },
  { districtId: "16", name: "Natore Sadar", bn: "নাটোর সদর" },
  { districtId: "16", name: "Singra", bn: "সিংড়া" },
  { districtId: "17", name: "Akkelpur", bn: "আক্কেলপুর" },
  { districtId: "17", name: "Joypurhat Sadar", bn: "জয়পুরহাট সদর" },
  { districtId: "17", name: "Kalai", bn: "কালাই" },
  { districtId: "17", name: "Khetlal", bn: "ক্ষেতলাল" },
  { districtId: "17", name: "Panchbibi", bn: "পাঁচবিবি" },
  { districtId: "18", name: "Bholahat", bn: "ভোলাহাট" },
  { districtId: "18", name: "Chapainawabganj Sadar", bn: "চাঁপাইনবাবগঞ্জ সদর" },
  { districtId: "18", name: "Gomostapur", bn: "গোমস্তাপুর" },
  { districtId: "18", name: "Nachol", bn: "নাচোল" },
  { districtId: "18", name: "Shibganj", bn: "শিবগঞ্জ" },
  { districtId: "19", name: "Atrai", bn: "আত্রাই" },
  { districtId: "19", name: "Badalgachi", bn: "বদলগাছী" },
  { districtId: "19", name: "Dhamoirhat", bn: "ধামইরহাট" },
  { districtId: "19", name: "Manda", bn: "মান্দা" },
  { districtId: "19", name: "Mohadevpur", bn: "মহাদেবপুর" },
  { districtId: "19", name: "Naogaon Sadar", bn: "নওগাঁ সদর" },
  { districtId: "19", name: "Niamatpur", bn: "নিয়ামতপুর" },
  { districtId: "19", name: "Patnitala", bn: "পত্নিতলা" },
  { districtId: "19", name: "Porsha", bn: "পোরশা" },
  { districtId: "19", name: "Raninagar", bn: "রাণীনগর" },
  { districtId: "19", name: "Sapahar", bn: "সাপাহার" },
  { districtId: "20", name: "Abhaynagar", bn: "অভয়নগর" },
  { districtId: "20", name: "Bagherpara", bn: "বাঘারপাড়া" },
  { districtId: "20", name: "Chougachha", bn: "চৌগাছা" },
  { districtId: "20", name: "Jessore Sadar", bn: "যশোর সদর" },
  { districtId: "20", name: "Jhikargacha", bn: "ঝিকরগাছা" },
  { districtId: "20", name: "Keshabpur", bn: "কেশবপুর" },
  { districtId: "20", name: "Manirampur", bn: "মণিরামপুর" },
  { districtId: "20", name: "Sharsha", bn: "শার্শা" },
  { districtId: "21", name: "Assasuni", bn: "আশাশুনি" },
  { districtId: "21", name: "Debhata", bn: "দেবহাটা" },
  { districtId: "21", name: "Kalaroa", bn: "কলারোয়া" },
  { districtId: "21", name: "Kaliganj", bn: "কালিগঞ্জ" },
  { districtId: "21", name: "Satkhira Sadar", bn: "সাতক্ষীরা সদর" },
  { districtId: "21", name: "Shyamnagar", bn: "শ্যামনগর" },
  { districtId: "21", name: "Tala", bn: "তালা" },
  { districtId: "22", name: "Gangni", bn: "গাংনী" },
  { districtId: "22", name: "Meherpur Sadar", bn: "মেহেরপুর সদর" },
  { districtId: "22", name: "Mujibnagar", bn: "মুজিবনগর" },
  { districtId: "23", name: "Kalia", bn: "কালিয়া" },
  { districtId: "23", name: "Lohagara", bn: "লোহাগড়া" },
  { districtId: "23", name: "Narail Sadar", bn: "নড়াইল সদর" },
  { districtId: "24", name: "Alamdanga", bn: "আলমডাঙ্গা" },
  { districtId: "24", name: "Chuadanga Sadar", bn: "চুয়াডাঙ্গা সদর" },
  { districtId: "24", name: "Damurhuda", bn: "দামুড়হুদা" },
  { districtId: "24", name: "Jibannagar", bn: "জীবননগর" },
  { districtId: "25", name: "Bheramara", bn: "ভেড়ামারা" },
  { districtId: "25", name: "Daulatpur", bn: "দৌলতপুর" },
  { districtId: "25", name: "Khoksa", bn: "খোকসা" },
  { districtId: "25", name: "Kumarkhali", bn: "কুমারখালী" },
  { districtId: "25", name: "Kushtia Sadar", bn: "কুষ্টিয়া সদর" },
  { districtId: "25", name: "Mirpur", bn: "মিরপুর" },
  { districtId: "26", name: "Magura Sadar", bn: "মাগুরা সদর" },
  { districtId: "26", name: "Mohammadpur", bn: "মহম্মদপুর" },
  { districtId: "26", name: "Shalikha", bn: "শালিখা" },
  { districtId: "26", name: "Sreepur", bn: "শ্রীপুর" },
  { districtId: "27", name: "Botiaghata", bn: "বটিয়াঘাটা" },
  { districtId: "27", name: "Dakop", bn: "দাকোপ" },
  { districtId: "27", name: "Digholia", bn: "দিঘলিয়া" },
  { districtId: "27", name: "Dumuria", bn: "ডুমুরিয়া" },
  { districtId: "27", name: "Fultola", bn: "ফুলতলা" },
  { districtId: "27", name: "Koyra", bn: "কয়রা" },
  { districtId: "27", name: "Paikgasa", bn: "পাইকগাছা" },
  { districtId: "27", name: "Rupsha", bn: "রূপসা" },
  { districtId: "27", name: "Terokhada", bn: "তেরখাদা" },
  { districtId: "28", name: "Bagerhat Sadar", bn: "বাগেরহাট সদর" },
  { districtId: "28", name: "Chitalmari", bn: "চিতলমারী" },
  { districtId: "28", name: "Fakirhat", bn: "ফকিরহাট" },
  { districtId: "28", name: "Kachua", bn: "কচুয়া" },
  { districtId: "28", name: "Mollahat", bn: "মোল্লাহাট" },
  { districtId: "28", name: "Mongla", bn: "মোংলা" },
  { districtId: "28", name: "Morrelganj", bn: "মোড়েলগঞ্জ" },
  { districtId: "28", name: "Rampal", bn: "রামপাল" },
  { districtId: "28", name: "Sarankhola", bn: "শরণখোলা" },
  { districtId: "29", name: "Harinakundu", bn: "হরিণাকুন্ডু" },
  { districtId: "29", name: "Jhenaidah Sadar", bn: "ঝিনাইদহ সদর" },
  { districtId: "29", name: "Kaliganj", bn: "কালীগঞ্জ" },
  { districtId: "29", name: "Kotchandpur", bn: "কোটচাঁদপুর" },
  { districtId: "29", name: "Moheshpur", bn: "মহেশপুর" },
  { districtId: "29", name: "Shailkupa", bn: "শৈলকুপা" },
  { districtId: "30", name: "Jhalakathi Sadar", bn: "ঝালকাঠি সদর" },
  { districtId: "30", name: "Kathalia", bn: "কাঠালিয়া" },
  { districtId: "30", name: "Nalchity", bn: "নলছিটি" },
  { districtId: "30", name: "Rajapur", bn: "রাজাপুর" },
  { districtId: "31", name: "Bauphal", bn: "বাউফল" },
  { districtId: "31", name: "Dashmina", bn: "দশমিনা" },
  { districtId: "31", name: "Dumki", bn: "দুমকি" },
  { districtId: "31", name: "Galachipa", bn: "গলাচিপা" },
  { districtId: "31", name: "Kalapara", bn: "কলাপাড়া" },
  { districtId: "31", name: "Mirzaganj", bn: "মির্জাগঞ্জ" },
  { districtId: "31", name: "Patuakhali Sadar", bn: "পটুয়াখালী সদর" },
  { districtId: "31", name: "Rangabali", bn: "রাঙ্গাবালী" },
  { districtId: "32", name: "Bhandaria", bn: "ভান্ডারিয়া" },
  { districtId: "32", name: "Kawkhali", bn: "কাউখালী" },
  { districtId: "32", name: "Mathbaria", bn: "মঠবাড়ীয়া" },
  { districtId: "32", name: "Nazirpur", bn: "নাজিরপুর" },
  { districtId: "32", name: "Nesarabad", bn: "নেছারাবাদ" },
  { districtId: "32", name: "Pirojpur Sadar", bn: "পিরোজপুর সদর" },
  { districtId: "32", name: "Zianagar", bn: "জিয়ানগর" },
  { districtId: "33", name: "Agailjhara", bn: "আগৈলঝাড়া" },
  { districtId: "33", name: "Babuganj", bn: "বাবুগঞ্জ" },
  { districtId: "33", name: "Bakerganj", bn: "বাকেরগঞ্জ" },
  { districtId: "33", name: "Banaripara", bn: "বানারীপাড়া" },
  { districtId: "33", name: "Barisal Sadar", bn: "বরিশাল সদর" },
  { districtId: "33", name: "Gournadi", bn: "গৌরনদী" },
  { districtId: "33", name: "Hizla", bn: "হিজলা" },
  { districtId: "33", name: "Mehendiganj", bn: "মেহেন্দিগঞ্জ" },
  { districtId: "33", name: "Muladi", bn: "মুলাদী" },
  { districtId: "33", name: "Wazirpur", bn: "উজিরপুর" },
  { districtId: "34", name: "Bhola Sadar", bn: "ভোলা সদর" },
  { districtId: "34", name: "Borhan Sddin", bn: "বোরহান উদ্দিন" },
  { districtId: "34", name: "Charfesson", bn: "চরফ্যাশন" },
  { districtId: "34", name: "Doulatkhan", bn: "দৌলতখান" },
  { districtId: "34", name: "Lalmohan", bn: "লালমোহন" },
  { districtId: "34", name: "Monpura", bn: "মনপুরা" },
  { districtId: "34", name: "Tazumuddin", bn: "তজুমদ্দিন" },
  { districtId: "35", name: "Amtali", bn: "আমতলী" },
  { districtId: "35", name: "Bamna", bn: "বামনা" },
  { districtId: "35", name: "Barguna Sadar", bn: "বরগুনা সদর" },
  { districtId: "35", name: "Betagi", bn: "বেতাগী" },
  { districtId: "35", name: "Pathorghata", bn: "পাথরঘাটা" },
  { districtId: "35", name: "Taltali", bn: "তালতলি" },
  { districtId: "36", name: "Balaganj", bn: "বালাগঞ্জ" },
  { districtId: "36", name: "Beanibazar", bn: "বিয়ানীবাজার" },
  { districtId: "36", name: "Bishwanath", bn: "বিশ্বনাথ" },
  { districtId: "36", name: "Companiganj", bn: "কোম্পানীগঞ্জ" },
  { districtId: "36", name: "Dakshinsurma", bn: "দক্ষিণ সুরমা" },
  { districtId: "36", name: "Fenchuganj", bn: "ফেঞ্চুগঞ্জ" },
  { districtId: "36", name: "Golapganj", bn: "গোলাপগঞ্জ" },
  { districtId: "36", name: "Gowainghat", bn: "গোয়াইনঘাট" },
  { districtId: "36", name: "Jaintiapur", bn: "জৈন্তাপুর" },
  { districtId: "36", name: "Kanaighat", bn: "কানাইঘাট" },
  { districtId: "36", name: "Osmaninagar", bn: "ওসমানী নগর" },
  { districtId: "36", name: "Sylhet Sadar", bn: "সিলেট সদর" },
  { districtId: "36", name: "Zakiganj", bn: "জকিগঞ্জ" },
  { districtId: "37", name: "Barlekha", bn: "বড়লেখা" },
  { districtId: "37", name: "Juri", bn: "জুড়ী" },
  { districtId: "37", name: "Kamolganj", bn: "কমলগঞ্জ" },
  { districtId: "37", name: "Kulaura", bn: "কুলাউড়া" },
  { districtId: "37", name: "Moulvibazar Sadar", bn: "মৌলভীবাজার সদর" },
  { districtId: "37", name: "Rajnagar", bn: "রাজনগর" },
  { districtId: "37", name: "Sreemangal", bn: "শ্রীমঙ্গল" },
  { districtId: "38", name: "Ajmiriganj", bn: "আজমিরীগঞ্জ" },
  { districtId: "38", name: "Bahubal", bn: "বাহুবল" },
  { districtId: "38", name: "Baniachong", bn: "বানিয়াচং" },
  { districtId: "38", name: "Chunarughat", bn: "চুনারুঘাট" },
  { districtId: "38", name: "Habiganj Sadar", bn: "হবিগঞ্জ সদর" },
  { districtId: "38", name: "Lakhai", bn: "লাখাই" },
  { districtId: "38", name: "Madhabpur", bn: "মাধবপুর" },
  { districtId: "38", name: "Nabiganj", bn: "নবীগঞ্জ" },
  { districtId: "39", name: "Bishwambarpur", bn: "বিশ্বম্ভরপুর" },
  { districtId: "39", name: "Chhatak", bn: "ছাতক" },
  { districtId: "39", name: "Derai", bn: "দিরাই" },
  { districtId: "39", name: "Dharmapasha", bn: "ধর্মপাশা" },
  { districtId: "39", name: "Dowarabazar", bn: "দোয়ারাবাজার" },
  { districtId: "39", name: "Jagannathpur", bn: "জগন্নাথপুর" },
  { districtId: "39", name: "Jamalganj", bn: "জামালগঞ্জ" },
  { districtId: "39", name: "Madhyanagar", bn: "মধ্যনগর" },
  { districtId: "39", name: "Shalla", bn: "শাল্লা" },
  { districtId: "39", name: "South Sunamganj", bn: "দক্ষিণ সুনামগঞ্জ" },
  { districtId: "39", name: "Sunamganj Sadar", bn: "সুনামগঞ্জ সদর" },
  { districtId: "39", name: "Tahirpur", bn: "তাহিরপুর" },
  { districtId: "40", name: "Belabo", bn: "বেলাবো" },
  { districtId: "40", name: "Monohardi", bn: "মনোহরদী" },
  { districtId: "40", name: "Narsingdi Sadar", bn: "নরসিংদী সদর" },
  { districtId: "40", name: "Palash", bn: "পলাশ" },
  { districtId: "40", name: "Raipura", bn: "রায়পুরা" },
  { districtId: "40", name: "Shibpur", bn: "শিবপুর" },
  { districtId: "41", name: "Gazipur Sadar", bn: "গাজীপুর সদর" },
  { districtId: "41", name: "Kaliakair", bn: "কালিয়াকৈর" },
  { districtId: "41", name: "Kaliganj", bn: "কালীগঞ্জ" },
  { districtId: "41", name: "Kapasia", bn: "কাপাসিয়া" },
  { districtId: "41", name: "Sreepur", bn: "শ্রীপুর" },
  { districtId: "42", name: "Bhedarganj", bn: "ভেদরগঞ্জ" },
  { districtId: "42", name: "Damudya", bn: "ডামুড্যা" },
  { districtId: "42", name: "Gosairhat", bn: "গোসাইরহাট" },
  { districtId: "42", name: "Naria", bn: "নড়িয়া" },
  { districtId: "42", name: "Shariatpur Sadar", bn: "শরিয়তপুর সদর" },
  { districtId: "42", name: "Zajira", bn: "জাজিরা" },
  { districtId: "43", name: "Araihazar", bn: "আড়াইহাজার" },
  { districtId: "43", name: "Bandar", bn: "বন্দর" },
  { districtId: "43", name: "Narayanganj Sadar", bn: "নারায়নগঞ্জ সদর" },
  { districtId: "43", name: "Rupganj", bn: "রূপগঞ্জ" },
  { districtId: "43", name: "Sonargaon", bn: "সোনারগাঁ" },
  { districtId: "44", name: "Basail", bn: "বাসাইল" },
  { districtId: "44", name: "Bhuapur", bn: "ভুয়াপুর" },
  { districtId: "44", name: "Delduar", bn: "দেলদুয়ার" },
  { districtId: "44", name: "Dhanbari", bn: "ধনবাড়ী" },
  { districtId: "44", name: "Ghatail", bn: "ঘাটাইল" },
  { districtId: "44", name: "Gopalpur", bn: "গোপালপুর" },
  { districtId: "44", name: "Kalihati", bn: "কালিহাতী" },
  { districtId: "44", name: "Madhupur", bn: "মধুপুর" },
  { districtId: "44", name: "Mirzapur", bn: "মির্জাপুর" },
  { districtId: "44", name: "Nagarpur", bn: "নাগরপুর" },
  { districtId: "44", name: "Sakhipur", bn: "সখিপুর" },
  { districtId: "44", name: "Tangail Sadar", bn: "টাঙ্গাইল সদর" },
  { districtId: "45", name: "Austagram", bn: "অষ্টগ্রাম" },
  { districtId: "45", name: "Bajitpur", bn: "বাজিতপুর" },
  { districtId: "45", name: "Bhairab", bn: "ভৈরব" },
  { districtId: "45", name: "Hossainpur", bn: "হোসেনপুর" },
  { districtId: "45", name: "Itna", bn: "ইটনা" },
  { districtId: "45", name: "Karimgonj", bn: "করিমগঞ্জ" },
  { districtId: "45", name: "Katiadi", bn: "কটিয়াদী" },
  { districtId: "45", name: "Kishoreganj Sadar", bn: "কিশোরগঞ্জ সদর" },
  { districtId: "45", name: "Kuliarchar", bn: "কুলিয়ারচর" },
  { districtId: "45", name: "Mithamoin", bn: "মিঠামইন" },
  { districtId: "45", name: "Nikli", bn: "নিকলী" },
  { districtId: "45", name: "Pakundia", bn: "পাকুন্দিয়া" },
  { districtId: "45", name: "Tarail", bn: "তাড়াইল" },
  { districtId: "46", name: "Doulatpur", bn: "দৌলতপুর" },
  { districtId: "46", name: "Gior", bn: "ঘিওর" },
  { districtId: "46", name: "Harirampur", bn: "হরিরামপুর" },
  { districtId: "46", name: "Manikganj Sadar", bn: "মানিকগঞ্জ সদর" },
  { districtId: "46", name: "Saturia", bn: "সাটুরিয়া" },
  { districtId: "46", name: "Shibaloy", bn: "শিবালয়" },
  { districtId: "46", name: "Singiar", bn: "সিংগাইর" },
  { districtId: "47", name: "Dhamrai", bn: "ধামরাই" },
  { districtId: "47", name: "Dohar", bn: "দোহার" },
  { districtId: "47", name: "Keraniganj", bn: "কেরাণীগঞ্জ" },
  { districtId: "47", name: "Nawabganj", bn: "নবাবগঞ্জ" },
  { districtId: "47", name: "Savar", bn: "সাভার" },
  { districtId: "48", name: "Gajaria", bn: "গজারিয়া" },
  { districtId: "48", name: "Louhajanj", bn: "লৌহজং" },
  { districtId: "48", name: "Munshiganj Sadar", bn: "মুন্সিগঞ্জ সদর" },
  { districtId: "48", name: "Sirajdikhan", bn: "সিরাজদিখান" },
  { districtId: "48", name: "Sreenagar", bn: "শ্রীনগর" },
  { districtId: "48", name: "Tongibari", bn: "টংগীবাড়ি" },
  { districtId: "49", name: "Baliakandi", bn: "বালিয়াকান্দি" },
  { districtId: "49", name: "Goalanda", bn: "গোয়ালন্দ" },
  { districtId: "49", name: "Kalukhali", bn: "কালুখালী" },
  { districtId: "49", name: "Pangsa", bn: "পাংশা" },
  { districtId: "49", name: "Rajbari Sadar", bn: "রাজবাড়ী সদর" },
  { districtId: "50", name: "Dasar", bn: "ডাসার" },
  { districtId: "50", name: "Kalkini", bn: "কালকিনি" },
  { districtId: "50", name: "Madaripur Sadar", bn: "মাদারীপুর সদর" },
  { districtId: "50", name: "Rajoir", bn: "রাজৈর" },
  { districtId: "50", name: "Shibchar", bn: "শিবচর" },
  { districtId: "51", name: "Gopalganj Sadar", bn: "গোপালগঞ্জ সদর" },
  { districtId: "51", name: "Kashiani", bn: "কাশিয়ানী" },
  { districtId: "51", name: "Kotalipara", bn: "কোটালীপাড়া" },
  { districtId: "51", name: "Muksudpur", bn: "মুকসুদপুর" },
  { districtId: "51", name: "Tungipara", bn: "টুংগীপাড়া" },
  { districtId: "52", name: "Alfadanga", bn: "আলফাডাঙ্গা" },
  { districtId: "52", name: "Bhanga", bn: "ভাঙ্গা" },
  { districtId: "52", name: "Boalmari", bn: "বোয়ালমারী" },
  { districtId: "52", name: "Charbhadrasan", bn: "চরভদ্রাসন" },
  { districtId: "52", name: "Faridpur Sadar", bn: "ফরিদপুর সদর" },
  { districtId: "52", name: "Madhukhali", bn: "মধুখালী" },
  { districtId: "52", name: "Nagarkanda", bn: "নগরকান্দা" },
  { districtId: "52", name: "Sadarpur", bn: "সদরপুর" },
  { districtId: "52", name: "Saltha", bn: "সালথা" },
  { districtId: "53", name: "Atwari", bn: "আটোয়ারী" },
  { districtId: "53", name: "Boda", bn: "বোদা" },
  { districtId: "53", name: "Debiganj", bn: "দেবীগঞ্জ" },
  { districtId: "53", name: "Panchagarh Sadar", bn: "পঞ্চগড় সদর" },
  { districtId: "53", name: "Tetulia", bn: "তেতুলিয়া" },
  { districtId: "54", name: "Birampur", bn: "বিরামপুর" },
  { districtId: "54", name: "Birganj", bn: "বীরগঞ্জ" },
  { districtId: "54", name: "Birol", bn: "বিরল" },
  { districtId: "54", name: "Bochaganj", bn: "বোচাগঞ্জ" },
  { districtId: "54", name: "Chirirbandar", bn: "চিরিরবন্দর" },
  { districtId: "54", name: "Dinajpur Sadar", bn: "দিনাজপুর সদর" },
  { districtId: "54", name: "Fulbari", bn: "ফুলবাড়ী" },
  { districtId: "54", name: "Ghoraghat", bn: "ঘোড়াঘাট" },
  { districtId: "54", name: "Hakimpur", bn: "হাকিমপুর" },
  { districtId: "54", name: "Kaharol", bn: "কাহারোল" },
  { districtId: "54", name: "Khansama", bn: "খানসামা" },
  { districtId: "54", name: "Nawabganj", bn: "নবাবগঞ্জ" },
  { districtId: "54", name: "Parbatipur", bn: "পার্বতীপুর" },
  { districtId: "55", name: "Aditmari", bn: "আদিতমারী" },
  { districtId: "55", name: "Hatibandha", bn: "হাতীবান্ধা" },
  { districtId: "55", name: "Kaliganj", bn: "কালীগঞ্জ" },
  { districtId: "55", name: "Lalmonirhat Sadar", bn: "লালমনিরহাট সদর" },
  { districtId: "55", name: "Patgram", bn: "পাটগ্রাম" },
  { districtId: "56", name: "Dimla", bn: "ডিমলা" },
  { districtId: "56", name: "Domar", bn: "ডোমার" },
  { districtId: "56", name: "Jaldhaka", bn: "জলঢাকা" },
  { districtId: "56", name: "Kishorganj", bn: "কিশোরগঞ্জ" },
  { districtId: "56", name: "Nilphamari Sadar", bn: "নীলফামারী সদর" },
  { districtId: "56", name: "Syedpur", bn: "সৈয়দপুর" },
  { districtId: "57", name: "Gaibandha Sadar", bn: "গাইবান্ধা সদর" },
  { districtId: "57", name: "Gobindaganj", bn: "গোবিন্দগঞ্জ" },
  { districtId: "57", name: "Palashbari", bn: "পলাশবাড়ী" },
  { districtId: "57", name: "Phulchari", bn: "ফুলছড়ি" },
  { districtId: "57", name: "Sadullapur", bn: "সাদুল্লাপুর" },
  { districtId: "57", name: "Saghata", bn: "সাঘাটা" },
  { districtId: "57", name: "Sundarganj", bn: "সুন্দরগঞ্জ" },
  { districtId: "58", name: "Baliadangi", bn: "বালিয়াডাঙ্গী" },
  { districtId: "58", name: "Haripur", bn: "হরিপুর" },
  { districtId: "58", name: "Pirganj", bn: "পীরগঞ্জ" },
  { districtId: "58", name: "Ranisankail", bn: "রাণীশংকৈল" },
  { districtId: "58", name: "Thakurgaon Sadar", bn: "ঠাকুরগাঁও সদর" },
  { districtId: "59", name: "Badargonj", bn: "বদরগঞ্জ" },
  { districtId: "59", name: "Gangachara", bn: "গংগাচড়া" },
  { districtId: "59", name: "Kaunia", bn: "কাউনিয়া" },
  { districtId: "59", name: "Mithapukur", bn: "মিঠাপুকুর" },
  { districtId: "59", name: "Pirgacha", bn: "পীরগাছা" },
  { districtId: "59", name: "Pirgonj", bn: "পীরগঞ্জ" },
  { districtId: "59", name: "Rangpur Sadar", bn: "রংপুর সদর" },
  { districtId: "59", name: "Taragonj", bn: "তারাগঞ্জ" },
  { districtId: "60", name: "Bhurungamari", bn: "ভুরুঙ্গামারী" },
  { districtId: "60", name: "Charrajibpur", bn: "চর রাজিবপুর" },
  { districtId: "60", name: "Chilmari", bn: "চিলমারী" },
  { districtId: "60", name: "Kurigram Sadar", bn: "কুড়িগ্রাম সদর" },
  { districtId: "60", name: "Nageshwari", bn: "নাগেশ্বরী" },
  { districtId: "60", name: "Phulbari", bn: "ফুলবাড়ী" },
  { districtId: "60", name: "Rajarhat", bn: "রাজারহাট" },
  { districtId: "60", name: "Rowmari", bn: "রৌমারী" },
  { districtId: "60", name: "Ulipur", bn: "উলিপুর" },
  { districtId: "61", name: "Jhenaigati", bn: "ঝিনাইগাতী" },
  { districtId: "61", name: "Nalitabari", bn: "নালিতাবাড়ী" },
  { districtId: "61", name: "Nokla", bn: "নকলা" },
  { districtId: "61", name: "Sherpur Sadar", bn: "শেরপুর সদর" },
  { districtId: "61", name: "Sreebordi", bn: "শ্রীবরদী" },
  { districtId: "62", name: "Bhaluka", bn: "ভালুকা" },
  { districtId: "62", name: "Dhobaura", bn: "ধোবাউড়া" },
  { districtId: "62", name: "Fulbaria", bn: "ফুলবাড়ীয়া" },
  { districtId: "62", name: "Gafargaon", bn: "গফরগাঁও" },
  { districtId: "62", name: "Gouripur", bn: "গৌরীপুর" },
  { districtId: "62", name: "Haluaghat", bn: "হালুয়াঘাট" },
  { districtId: "62", name: "Iswarganj", bn: "ঈশ্বরগঞ্জ" },
  { districtId: "62", name: "Muktagacha", bn: "মুক্তাগাছা" },
  { districtId: "62", name: "Mymensingh Sadar", bn: "ময়মনসিংহ সদর" },
  { districtId: "62", name: "Nandail", bn: "নান্দাইল" },
  { districtId: "62", name: "Phulpur", bn: "ফুলপুর" },
  { districtId: "62", name: "Tarakanda", bn: "তারাকান্দা" },
  { districtId: "62", name: "Trishal", bn: "ত্রিশাল" },
  { districtId: "63", name: "Bokshiganj", bn: "বকশীগঞ্জ" },
  { districtId: "63", name: "Dewangonj", bn: "দেওয়ানগঞ্জ" },
  { districtId: "63", name: "Islampur", bn: "ইসলামপুর" },
  { districtId: "63", name: "Jamalpur Sadar", bn: "জামালপুর সদর" },
  { districtId: "63", name: "Madarganj", bn: "মাদারগঞ্জ" },
  { districtId: "63", name: "Melandah", bn: "মেলান্দহ" },
  { districtId: "63", name: "Sarishabari", bn: "সরিষাবাড়ী" },
  { districtId: "64", name: "Atpara", bn: "আটপাড়া" },
  { districtId: "64", name: "Barhatta", bn: "বারহাট্টা" },
  { districtId: "64", name: "Durgapur", bn: "দুর্গাপুর" },
  { districtId: "64", name: "Kalmakanda", bn: "কলমাকান্দা" },
  { districtId: "64", name: "Kendua", bn: "কেন্দুয়া" },
  { districtId: "64", name: "Khaliajuri", bn: "খালিয়াজুরী" },
  { districtId: "64", name: "Madan", bn: "মদন" },
  { districtId: "64", name: "Mohongonj", bn: "মোহনগঞ্জ" },
  { districtId: "64", name: "Netrokona Sadar", bn: "নেত্রকোণা সদর" },
  { districtId: "64", name: "Purbadhala", bn: "পূর্বধলা" },
]

export function upazilasFor(districtId: string): BdUpazila[] {
  return BD_UPAZILAS.filter((u) => u.districtId === districtId)
}
